### PR TITLE
Upgrade AGP to 7.1.2 & Gradle to 7.2 - rebase

### PR DESCRIPTION
**Pull request by jrtberlin**
Original PR is here: https://github.com/AsteroidOS/AsteroidOSSync/pull/155#issuecomment-1094226412

### CODE REVIEW

**Review by MagneFire — CHANGES_REQUESTED** [review]
In general this looks okay.
Just a few comments regarding some individual commits:
- https://github.com/AsteroidOS/AsteroidOSSync/pull/161/commits/6bcd9948bbd260ed05134dc712d6766232c99a92: Is this TODO tested?
- https://github.com/AsteroidOS/AsteroidOSSync/pull/161/commits/3e4ff91725b3a9de028869a488f3e6f6d1544c38: Lots of 'Will be obsolete soon'. When will this 'soon' be? And what will we do about this?
- https://github.com/AsteroidOS/AsteroidOSSync/pull/161/commits/f15dd5ee5e65f1dde1e6e8065246471574cd4d98: Remove the ASCII style emoji here.
- https://github.com/AsteroidOS/AsteroidOSSync/pull/161/commits/682c6ad69c1f86ba7f1e14a3e5165ad6c821731f: Commit body is not okay. Leave your opinion out of this.
- https://github.com/AsteroidOS/AsteroidOSSync/pull/161/commits/5f3124bc9cd63ff60129e38a46e75c64bb497c54: Lots of TODO's, we should probably remove them and make a separate Github issue for it?

**Comment by Doomsdayrs** [comment]
>* [6bcd994](https://github.com/AsteroidOS/AsteroidOSSync/commit/6bcd9948bbd260ed05134dc712d6766232c99a92): Is this TODO tested?

The reason for the TODO to exist is due to using reflection to access private variables. In later versions of android you have no clue if the code will even work anymore or not. That is why that is there

>* [3e4ff91](https://github.com/AsteroidOS/AsteroidOSSync/commit/3e4ff91725b3a9de028869a488f3e6f6d1544c38): Lots of 'Will be obsolete soon'. When will this 'soon' be? And what will we do about this?

Soon will be when it either starts lagging, not building etc. The best solution is to move to jetpack compose and create a new UI for it. I can do this in a separate PR later as it is currently still working.

>* [f15dd5e](https://github.com/AsteroidOS/AsteroidOSSync/commit/f15dd5ee5e65f1dde1e6e8065246471574cd4d98): Remove the ASCII style emoji here.

:P It is a nice bit of humor in the code. I hope you can agree :D

>* [682c6ad](https://github.com/AsteroidOS/AsteroidOSSync/commit/682c6ad69c1f86ba7f1e14a3e5165ad6c821731f): Commit body is not okay. Leave your opinion out of this.

I do not see an opinion. Android provides certain colors as part of the system, so the person who added the line at some point either was copying and pasting or does not have an adequate understanding of android development.

>* [5f3124b](https://github.com/AsteroidOS/AsteroidOSSync/commit/5f3124bc9cd63ff60129e38a46e75c64bb497c54): Lots of TODO's, we should probably remove them and make a separate Github issue for it?

I agree, this is something that should be worked on. Once this is merged the issue can be made. (as this provides the backbone for the future code)

**Comment by FlorentRevest** [comment]
> > * [682c6ad](https://github.com/AsteroidOS/AsteroidOSSync/commit/682c6ad69c1f86ba7f1e14a3e5165ad6c821731f): Commit body is not okay. Leave your opinion out of this.
> 
> I do not see an opinion. Android provides certain colors as part of the system, so the person who added the line at some point either was copying and pasting or does not have an adequate understanding of android development.

No, this is not okay and I'm surprised you don't even recognize it. Debating at a technical level is always welcome and here your technical analysis ("Android provides certain colors as part of the system") is a totally valid point but attacking another community member at a personal level ("Who, just *who* does this?") is *never* ok. Please refer to https://asteroidos.org/wiki/code-of-conduct/ and be respectful of other community members. I will oppose merging this PR as long as this sort of comment will be in the commit log.

**Comment by Doomsdayrs** [comment]
> > > * [682c6ad](https://github.com/AsteroidOS/AsteroidOSSync/commit/682c6ad69c1f86ba7f1e14a3e5165ad6c821731f): Commit body is not okay. Leave your opinion out of this.
> > 
> > 
> > I do not see an opinion. Android provides certain colors as part of the system, so the person who added the line at some point either was copying and pasting or does not have an adequate understanding of android development.
> 
> No, this is not okay and I'm surprised you don't even recognize it. Debating at a technical level is always welcome and here your technical analysis ("Android provides certain colors as part of the system") is a totally valid point but attacking another community member at a personal level ("Who, just _who_ does this?") is _never_ ok. Please refer to https://asteroidos.org/wiki/code-of-conduct/ and be respectful of other community members. I will oppose merging this PR as long as this sort of comment will be in the commit log.

Alright, @jrtberlin Can you drop the commit?

**Comment by Doomsdayrs** [comment]
Bump for visibility

**Comment by MagneFire** [comment]
The main comment that should be addressed is the amount of `TODO`s in code. We should use `TODO`s in code as a means to remind someone that they have to take a look at something before it's merged. As in the one that introduced the `TODO` should also be the one to fix it.
As a reminder to remove/fix/optimize something before a PR is made.

I also see what your intention is with regards to `TODO`s. Use it in conjunction with the GitHub issue system to link between an issue and a specific `TODO`. But this will lead to a huge amount of `TODO`s in code that probably no-one will address.

> > * [6bcd994](https://github.com/AsteroidOS/AsteroidOSSync/commit/6bcd9948bbd260ed05134dc712d6766232c99a92): Is this TODO tested?
> 
> The reason for the TODO to exist is due to using reflection to access private variables. In later versions of android you have no clue if the code will even work anymore or not. That is why that is there
> 

The use of private API's is indeed not good! But instead of the `TODO` use a GitHub issue that specifically links to this part of the code (the entire block) that explains what these classes do and what potential solution we could use  here.

> > * [3e4ff91](https://github.com/AsteroidOS/AsteroidOSSync/commit/3e4ff91725b3a9de028869a488f3e6f6d1544c38): Lots of 'Will be obsolete soon'. When will this 'soon' be? And what will we do about this?
> 
> Soon will be when it either starts lagging, not building etc. The best solution is to move to jetpack compose and create a new UI for it. I can do this in a separate PR later as it is currently still working.
> 

My point is that soon defines a timeline of sorts, but nothing concrete. Again, a GitHub issue is the perfect place to notify that the used library is no longer maintained and we should look into a different solution (jetpack compose like you mentioned).

> > * [f15dd5e](https://github.com/AsteroidOS/AsteroidOSSync/commit/f15dd5ee5e65f1dde1e6e8065246471574cd4d98): Remove the ASCII style emoji here.
> 
> :P It is a nice bit of humor in the code. I hope you can agree :D
> 

While humor is fine in chat and to some extend issues. I don't think it makes sense to put this in code.
Code should be objective or contain a constructive comment why things are the way they are.
For instance, I would replace that comment to say something like:
```
// Ignore violation of play store content since we rely on it to get notifications while the phone is in sleep mode.
```

> > * [5f3124b](https://github.com/AsteroidOS/AsteroidOSSync/commit/5f3124bc9cd63ff60129e38a46e75c64bb497c54): Lots of TODO's, we should probably remove them and make a separate Github issue for it?
> 
> I agree, this is something that should be worked on. Once this is merged the issue can be made. (as this provides the backbone for the future code)

The huge amount of `TODO`'s make the code look messy. It's duplicated code for which we could also use a function that would correctly handle this.

**Comment by jrtberlin** [comment]
Closing in favour of #165

**Pull request closed without merging**
