### PR TITLE
Don't notify for updated notifications

### PR DESCRIPTION
**Pull request by TheLastProject**
Currently, [every time a notification is updated](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Updating), the update is sent as a new notification. As notification updates are most commonly used for minor changes, this can cause some annoying situations. As an example, the app [Alarm Klock](https://f-droid.org/repository/browse/?fdid=com.angrydoughnuts.android.alarmclock) updates its notification every minute to show the time remaining until the next alarm, causing the watch to show a notification for this every minute.

As I see it (if you see a better way, feel free to implement it as such), the correct way to deal with this appears to, [in the onNotificationPosted call](https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/services/NLService.java#L134), store the notification ID and package name (as IDs are unique per package according to https://developer.android.com/reference/android/app/NotificationManager.html#notify(int,%20android.app.Notification)) so that the next time it gets posted, no new notification is shown. Of course, this list of apps and their posted IDs needs to have the ID removed again [in the onNotificationRemoved call](https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/services/NLService.java#L174). Android does not seem to have a function call to check this.

I have attempted to implement that in this pull request. Please note that this code is **UNTESTED** as I do not have the Android SDK set up and thus cannot currently compile Android apps. The code may very well not work, but I figured that if this doesn't work, it could at least be useful pseudocode.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
Hi,

This is an interesting bug report and commit but this is not how I want to implement it. On the watch, the FreeDesktop.org's notify standard is used to show notifications and it describes the usage of a "replace ID" field.

https://github.com/AsteroidOS/AsteroidOSSync/blob/master/app/src/main/java/org/asteroidos/sync/ble/NotificationService.java#L84
https://github.com/AsteroidOS/asteroid-btsyncd/blob/master/notificationservice.cpp#L41
https://github.com/AsteroidOS/asteroid-btsyncd/blob/master/notificationservice.cpp#L60

If this field would be correctly used on the lipstick/asteroid-launcher side, we could update notifications at the same time as they are updated on the phone. This should be the only proper fix.

Florent

**Comment by TheLastProject** [comment]
That indeed sounds better, although I unfortunately cannot tell from the freedesktop.org standard if "Replaces ID" are also per-app like in Android or global. I will assume global as the application name seems optional, in which case some kind of mapping may still be necessary.

**Comment by FlorentRevest** [comment]
A correct fix should have been implemented in https://github.com/AsteroidOS/asteroid-btsyncd/commit/5aa3c6e633ad388acd649e17c825ea1e58b33196 can you confirm if it closes the issue ?

**Comment by TheLastProject** [comment]
Assuming Korak's build of 19:54:08 contains this patch, it unfortunately still isn't fix. An easy way to check is simply downloading an app from F-Droid. Only one notification should appear, but multiple appear.

**Comment by nielstholenaar** [comment]
For anyone who is interested in the latest build: http://nielstholenaar.nl/app-debug.apk
That APK is based on my fork (https://github.com/nielstholenaar/AsteroidOSSync) which at the moment only contains one extra commit, that updates the gradle build dependencies to the latest version.

**Comment by TheLastProject** [comment]
I tried my own new build of the APK but even with that and a recent build of AsteroidOS itself I still experience these issues.

**Comment by FlorentRevest** [comment]
Should have been fixed for a while now and the PR isn't mergeable anymore

**Pull request closed without merging**
