### PR TITLE
Upgrade AGP to 7.1.2 & Gradle to 7.2

### PR DESCRIPTION
**Pull request by Doomsdayrs**
To help keep the app up to spec with gradle changes

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
Please note that easyweather has been changed to code-crusher due jcenter going down.

I suggest moving to another library eventually or using another service on device. Such as UnifiedNlp or other location providing libraries.

**Comment by Doomsdayrs** [comment]
It says it passes on my PC, any ideas?

**Comment by Doomsdayrs** [comment]
The CI is clearly completely broken.

**Comment by jrtberlin** [comment]
> @FlorentRevest 99% of the PR was me trying to do lint fixes to get the CI to build. Only the first commit is relevant

Should get resolved via https://github.com/AsteroidOS/AsteroidOSSync/pull/159

**Comment by Doomsdayrs** [comment]
HOW THE #### IS IT NOT HAPPY?

**Comment by jrtberlin** [comment]
I rebased it here https://github.com/jrtberlin/AsteroidOSSync/tree/rebase_agp_gradle 
The checks pass https://github.com/jrtberlin/AsteroidOSSync/actions/runs/2143428266

I left 2-3 commits out that edited the strings.xml files.

**Comment by FlorentRevest** [comment]
@Doomsdayrs if you drop [Fix lint issues with attempting to get a device name](https://github.com/AsteroidOS/AsteroidOSSync/pull/155/commits/bfa65bc037e00d72d311805a5527c527440c4b30) and rebase your PR it should be ready to merge then ;)

**Pull request closed without merging**
