### PR TITLE
Gradle upgrade

### LINKED ISSUE #135: replace the jcenter repository
The JCenter repository is [deprecated and going forward read-only](https://developer.android.com/studio/build/jcenter-migration).

We can replace `jcenter()` with `mavenCentral()` except for the `github.vatsal.easyweather` library. 
The options are:
- look for an alternative trusted repository
- replace the library (either new lib or self-implement the functionality)
- place the dependency in our tree.

### PR DESCRIPTION
**Pull request by Doomsdayrs**
- Upgrade Gradle to latest version
- Upgrade dependencies
- Remove jcenter with mavenCentral
- Replace vatsal EasyWeather with code-crusher EasyWeather

Closes #135

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
Ah yes, ` java.lang.reflect.InvocationTargetException (no error message)` very informative

**Comment by Doomsdayrs** [comment]
Run it again, It seems to fail the first time

**Comment by Doomsdayrs** [comment]
99% of these lint issues are because of importing other libraries directly.

They must be moved out to their own projects.

**Comment by MagneFire** [comment]
This is great work and a welcome change!

Terribly sorry that we didn't give an update on why this isn't merged yet.

But there's only one reason why we haven't merged it, and that is because this PR has some breaking changes which we will need to be tested before a new release.

As our previous release was some time ago we went ahead and tagged a new release. Once this is completed and we can further look into this PR.

I think @jrtberlin can give some more exact details on this, but he's currently a bit busy so this may take some time.

**Pull request closed without merging**
